[["C:/Users/USER/anaconda3/Lib/site-packages/service_identity/__init__.py",[false,[["CertificateError",true,2,["CertificateError","C:/Users/USER/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]],["SubjectAltNameWarning",true,2,["SubjectAltNameWarning","C:/Users/USER/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]],["VerificationError",true,2,["VerificationError","C:/Users/USER/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]]]]]]